spring:
  application:
    name: ${SPRING_APP_NAME:security}
  security:
    user:
      # if environment variable of "SECURITY_USERNAME" is provided
      # then it will be used else it will use "felix"
      name: ${SECURITY_USERNAME:felix}
      password: ${SECURITY_PASSWORD:felix123}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

